### ISSUE TITLE
Is Modal broken?

### ISSUE THREAD

**Issue by littledot** [themesberg/flowbite-vue#104]
I did a fresh install of flowbite-vue to try out Modals. However, I cannot get it to appear even using the demo code in the docs. Your Modal discards the background div and adds `hidden` to the Modal div.

To repro:
```
git clone git@github.com:littledot/flowbite-bug-report.git
npm install
npm run dev
# Click on Modal button
```

**Comment by MartinNiederl** [comment]
Have the same (or a similar problem)

Copying the code from https://flowbite-vue.com/components/modal/modal.html

Clicking the button inserts the following `div` into the DOM.

```html
<div id="defaultModal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 w-full md:inset-0 h-modal md:h-full">
...
</div>
```

But because it has `class="hidden"`, the **modal is not visible**.

When manually removing the `hidden` class in the inspector, the modal is visible in the top left of the screen (not sure if that location is expected). But **clicking any buttons** or the cross on the modal **do not have any effect**.

![image](https://user-images.githubusercontent.com/22956128/203034219-e8668404-3fab-4235-86b3-46bce13bbb6e.png)

**Comment by MartinNiederl** [comment]
Looks like there is an already merged pull request https://github.com/themesberg/flowbite-vue/pull/78 from quite a while ago which does not have this issue but is not published to [npmjs.com](https://www.npmjs.com/package/flowbite-vue) yet.

**Comment by cogor** [comment]
Thank you for the issue, Modal component will work next release
