### ISSUE TITLE
Progress Component - `Type 'string' is not assignable to type 'number'.`

### ISSUE THREAD

**Issue by kresimirko** [themesberg/flowbite-vue#140]
TypeScript type checking yields an error when using the progress component:

![image](https://user-images.githubusercontent.com/104278083/230473078-214aef32-f264-49f3-91c9-4a6de28e7454.png)

**Comment by josipgagro** [comment]
Since it is defined in `Progress.vue` for `progress` prop to be `Number` you need to pass it as a `Number`.
In your example you're passing `progress` as static prop, which is `String`.
Try changing `progress="45"` to `:progress="45"`, which is dynamic prop and it will be passed as a number.
More info can be found on: https://vuejs.org/guide/components/props.html#prop-passing-details

**Comment by cogor** [comment]
As @josipgagro said, you need to provide a number, not a string.
